server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/karimhmadi/config-server-service.git
          uri: https://github.com/docker12051981/config-server.git
          clone-on-start: true

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: eureka-0
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

